spring.application.name=attendance-service
server.port=8082


# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/quorum_placement
spring.datasource.username=root
spring.datasource.password=Root@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false


# Kafka consumer
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=attendance-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.quorum.attendanceservice.event.DriveScheduledEvent
