spring.application.name=placement-service

server.port=8081

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/quorum_placement
spring.datasource.username=root
spring.datasource.password=Root@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Kafka
spring.kafka.bootstrap-servers=localhost:9092